version: '3.3'
services:
  typebot-db:
    image: postgres:13
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=typebot
      - POSTGRES_PASSWORD=typebot

  typebot-builder:
    ports:
      - 3001:3000
    image: baptistearno/typebot-builder:latest
    restart: always
    depends_on:
      - typebot-db
    environment: 
      - DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
      - NEXTAUTH_URL=http://<coloque aqui o IP da sua VPS>:3001
      - NEXT_PUBLIC_VIEWER_URL=http://<coloque aqui o IP da sua VPS>:3002
      - ENCRYPTION_SECRET=875c916244442f7d89a8f376d9d33cac
      - ADMIN_EMAIL=<coloque aqui o seu Gmail>
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=465
      - SMTP_USERNAME=<coloque aqui o seu Gmail>
      - SMTP_PASSWORD=<coloque aqui a senha do seu Gmail (senha do App)>
      - SMTP_SECURE=true
      - NEXT_PUBLIC_SMTP_FROM='Suporte Typebot' <<coloque aqui o seu Gmail>>
      - S3_ACCESS_KEY=minio
      - S3_SECRET_KEY=minio123
      - S3_BUCKET=typebot
      - S3_ENDPOINT=http://<coloque aqui o IP da sua VPS>:9000

  typebot-viewer:
    ports:
      - 3002:3000
    image: baptistearno/typebot-viewer:latest
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
      - NEXT_PUBLIC_VIEWER_URL=http://<coloque aqui o IP da sua VPS>:3002
      - NEXTAUTH_URL=http://<coloque aqui o IP da sua VPS>:3001
      - ENCRYPTION_SECRET=875c916244442f7d89a8f376d9d33cac
      - S3_ACCESS_KEY=minio
      - S3_SECRET_KEY=minio123
      - S3_BUCKET=typebot
      - S3_ENDPOINT=http://<coloque aqui o IP da sua VPS>:9000

  mail:
    image: bytemark/smtp
    restart: always

  minio:
    image: minio/minio
    command: server /data
    ports:
      - '9000:9000'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - s3_data:/data

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc config host add minio http://minio:9000 minio minio123;
      /usr/bin/mc mb minio/typebot;
      /usr/bin/mc anonymous set public minio/typebot/public;
      exit 0;
      "

volumes:
  db_data:
  s3_data:
